### ISSUE TITLE
随机武器更新

### ISSUE THREAD

**Issue by paul-sama** [Skyminers/Bot-Splatoon3#1]
随机到的武器只有无印，似乎还少几个新武器。需要更新

**Comment by Skyminers** [comment]
随机武器的图片是从一个 wiki 上直接扒下来的，那个 wiki 现在一直没有更新，所以这里也暂时无法提供新武器。

**Comment by Skyminers** [comment]
目前的最新提交中随机武器已更新全部武器，UI 后续会进一步优化。功能已经可以使用了
