### ISSUE TITLE
[建议]能否添加代理选项

### ISSUE THREAD

**Issue by Hana-Akira** [Skyminers/Bot-Splatoon3#20]
不能直接访问很苦恼，之前更新是自己加代理解决。这次更换成cfscrape不太会弄了Otz

**Comment by Cypas** [comment]
我之前本地环境测试时也是需要梯子，最近splatoon.ink加cf后裸连倒也能跑了，你可以先试试

**Comment by Hana-Akira** [comment]
今晚我也试过了，可能是因为走V4的原因污染太严重了。还是无法访问

**Comment by Cypas** [comment]
nb2的应用配置还不太会，明天试试看

**Comment by Cypas** [comment]
1.1.0版本已更新代理配置项，可以安装最新版试试，我这边用的是基于nonebot2框架魔改的zhenxunbot框架，但因为版本更新太慢已经无法兼容现在nb2的环境配置项了，抱歉我自己没法测试功能是否可用，只能麻烦你帮忙测试

**Comment by Hana-Akira** [comment]
可以使用，需要把utils.py第31行内容改下："https": "http://{}".format(proxy_address),
本地代理一般走不了S的

**Comment by Cypas** [comment]
已更新1.1.3，为其他httpx请求,playwright请求也添加了代理配置；武器图片爬取改为异步处理，不会再干扰其他插件命令处理
