### ISSUE TITLE
[建议]有考虑过给随机武器增加地图和模式吗

### ISSUE THREAD

**Issue by PBnicad** [Skyminers/Bot-Splatoon3#33]
能否给随机武器增加地图和模式
![d654d7b9eeda69a846fbb85db7e85447](https://github.com/Skyminers/Bot-Splatoon3/assets/36125594/e391e602-1bba-429d-a31a-3fa2fa6e07b2)

**Comment by Skyminers** [comment]
OK，后续更新代码会考虑添加这部分的

**Comment by Cypas** [comment]
splatoon3私房本就可以选择随机地图模式，若在插件内添加随机地图，反而会让游戏内选图需要跟随插件的选图来进行选择，这样的行为显得本末倒置了；
至于游戏模式也只是4种真格模式内进行选择，这并不需要什么随机性，随手切换更为方便；

综合以上因素，插件不考虑随机武器增加地图和模式这一功能，如有个人特殊需求，请二次进行开发

**Comment by PBnicad** [comment]
好的
