### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by paul-sama** [Skyminers/Bot-Splatoon3#7]
https://github.com/Skyminers/Bot-Splatoon3/blob/673a621a17f2e7198f61072dd238767f7c098e71/nonebot_plugin_splatoon3/image.py#L34
和

https://github.com/Skyminers/Bot-Splatoon3/blob/673a621a17f2e7198f61072dd238767f7c098e71/nonebot_plugin_splatoon3/__init__.py#L271

RecursionError: maximum recursion depth exceeded

/装备
/活动
/祭典
这三个貌似没更新代码

**Comment by Cypas** [comment]
刚刚把对战的ui界面改完，活动和祭典的功能还要过几天，帮助等完成全部代码后再写
